import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/lib/utils.ts",
    "src/hooks/use-mobile.tsx",
    "src/components/ui/*.tsx",
  ],
  format: ["esm"],
  dts: true,
  splitting: true,
  sourcemap: true,
  clean: true,
  outDir: "dist",
  external: [
    "react",
    "react-dom",
    /^@radix-ui\//,
    "class-variance-authority",
    "clsx",
    "tailwind-merge",
    "lucide-react",
    "cmdk",
    "embla-carousel-react",
    "input-otp",
    "react-day-picker",
    "react-hook-form",
    "@hookform/resolvers",
    "react-resizable-panels",
    "recharts",
    "sonner",
    "vaul",
  ],
});
